apiVersion: v1
kind: PersistentVolume
metadata:
  name: niles-media
spec:
  capacity:
    storage: 100Gi  
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /srv/media
    server: niles
  persistentVolumeReclaimPolicy: Recycle


