apiVersion: v1
kind: PersistentVolume
metadata:
  name: niles-dev
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /srv/dev
    server: niles
  persistentVolumeReclaimPolicy: Recycle