apiVersion: v1
kind: PersistentVolume
metadata:
  name: niles-storage
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs: 
    path: /srv/kubes/configs/
    server: 10.1.1.3
  persistentVolumeReclaimPolicy: Recycle
