apiVersion: apps/v1
kind: Deployment
metadata:
  name: icecast
spec:
  selector:
    matchLabels:
      app: icecast
  replicas: 1
  template:
    metadata:
      labels:
        app: icecast
    spec:
      containers:
        - name: icecast
          image: fergalmoran/icecast
          ports:
            - containerPort: 8000
