apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: functions/prometheus:2.2.0-armhf
        command:
          - "prometheus"
          - "--config.file=/etc/prometheus/prometheus.yml"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          requests:
            memory: 250Mi
          limits:
            memory: 250Mi
        volumeMounts:
        - name: niles-storage
          mountPath: /etc/prometheus/
          subPath: "prometheus/etc"
      volumes:
        - name: niles-storage
          persistentVolumeClaim:
            claimName: niles-storage-claim
