FROM arm32v7/ubuntu:17.10

ENV DEBIAN_FRONTEND noninteractive

# Set locale to UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LANG en_US.UTF-8
RUN apt-get clean && apt-get update && apt-get install -y locales

RUN locale-gen en_US en_US.UTF-8
RUN update-locale LANG=en_US.UTF-8
RUN dpkg-reconfigure locales

# Update ubuntu
RUN apt-get dist-upgrade -qy && apt-get -q update
RUN apt-get install -qy --force-yes libmono-cil-dev libgdiplus unzip wget
RUN mkdir MBServer && cd MBServer &&  wget -O MBServer.Mono.zip https://github.com/MediaBrowser/Emby/releases/download/3.4.1.13/Emby.Mono.zip && unzip MBServer.Mono.zip
RUN apt-get -y autoremove && rm /MBServer/MBServer.Mono.zip

VOLUME /MediaBrowser.Mono.docker/ProgramData-Server

ADD ./start.sh /start.sh
RUN chmod u+x  /start.sh

EXPOSE 8096

ENTRYPOINT ["/start.sh"]
