apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: fg2it/grafana-armhf:v4.1.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: niles-storage
              mountPath: /var/lib/grafana/
              subPath: "grafana/var/lib/grafana"
            - name: niles-storage
              mountPath: /usr/share/grafana/
              subPath: "grafana/usr/share/grafana"
      volumes:
        - name: niles-storage
          persistentVolumeClaim:
            claimName: niles-storage-claim
