apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
spec:
  selector:
    matchLabels:
      app: jackett
  replicas: 1
  template:
    metadata:
      labels:
        app: jackett
    spec:
      containers:
        - name: jackett
          image: fergalmoran/jackett
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9117
          volumeMounts:
            - name: niles-storage
              mountPath: /config
              subPath: "jackett"
      volumes:
        - name: niles-storage
          persistentVolumeClaim:
            claimName: niles-storage-claim