apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
spec:
  selector:
    matchLabels:
      app: transmission
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          image: fergalmoran/transmission
          env:
            - name: CONFIG
              value: /config
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          ports:
            - containerPort: 9091
          volumeMounts:
            - name: niles-media
              mountPath: /srv/media/staging/transmission
              subPath: "staging/transmission"
            - name: niles-storage
              mountPath: /config
              subPath: "transmission"
      volumes:
        - name: niles-media
          persistentVolumeClaim:
            claimName: niles-media-claim
        - name: niles-storage
          persistentVolumeClaim:
            claimName: niles-storage-claim
